# Generated by Django 4.1.5 on 2023-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_staffed', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FL', 'Female'), ('O', 'Other'), ('PRNS', 'Prefer Not to Say')], default='ML', max_length=4)),
            ],
        ),
    ]
