# Generated by Django 4.1.5 on 2023-01-11 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='title',
            field=models.CharField(choices=[('TL', 'Team lead'), ('ML', 'Mid Lead'), ('JR', 'Junior')], default='JR', max_length=2),
        ),
    ]
