# Generated by Django 4.1.5 on 2023-01-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_created_date_personnel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='personnel.department'),
        ),
    ]
