# Generated by Django 4.1.5 on 2023-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer Not to Say')], default='Male', max_length=17),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.CharField(choices=[('Team Lead', 'Team lead'), ('Mid Lead', 'Mid Lead'), ('Junior', 'Junior')], default='Junior', max_length=9),
        ),
    ]
