# Generated by Django 4.1.5 on 2023-01-15 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0004_alter_personnel_gender_alter_personnel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='created_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_staffed',
        ),
        migrations.AddField(
            model_name='personnel',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salary',
            field=models.IntegerField(default=1250),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personals', to='personnel.department'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Other', 'O'), ('Prefer Not Say', 'N')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.CharField(choices=[('Team Lead', 'LEAD'), ('Mid Lead', 'MID'), ('Junior', 'JUN')], max_length=50),
        ),
    ]
